language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
notifications:
  on_success: change
